// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineRepository.Models.Entities;

public partial class PaymentMethodsBooking
{
    public int IdPaymentMethodsBooking { get; set; }

    public int? PaymentMethodId { get; set; }

    public int? BookingId { get; set; }

    public decimal? Price { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual PaymentMethod PaymentMethod { get; set; }
}