// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineRepository.Models.Entities;

public partial class PaymentMethod
{
    public int PaymentMethodId { get; set; }

    public string MethodName { get; set; }

    public int? Recharge { get; set; }

    public virtual ICollection<PaymentMethodsBooking> PaymentMethodsBookings { get; set; } = new List<PaymentMethodsBooking>();
}