// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CineRepository.Models.Entities;

public partial class Review
{
    public int ReviewId { get; set; }

    public int? MovieId { get; set; }

    public int? UserAccountId { get; set; }

    public int? Rating { get; set; }

    public string Comment { get; set; }

  [JsonIgnore]
  public virtual Movie Movie { get; set; }

    public virtual UserAccount UserAccount { get; set; }
}