// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CineRepository.Models.Entities;

public partial class Ticket
{
    public int TicketId { get; set; }

    public int? ShowtimeId { get; set; }

    public int? BookingId { get; set; }

    public string SeatNumber { get; set; }

    public DateTime? SaleDate { get; set; }

    public decimal? Price { get; set; }

  [JsonIgnore]
    public virtual Booking Booking { get; set; }

    public virtual Showtime Showtime { get; set; }
}