// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CineRepository.Models.Entities;

public partial class UserMovieHistory
{
    public int HistoryId { get; set; }

    public int? UserAccountId { get; set; }

    public int? MovieId { get; set; }

    public DateTime ViewedDate { get; set; }

    public virtual Movie Movie { get; set; }

    public virtual UserAccount UserAccount { get; set; }
}