// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace CineRepository.Models.Entities;

public partial class UserAccount
{
    public int UserAccountId { get; set; }

    public int? CustomerId { get; set; }

    public string Username { get; set; }

    public string PasswordHash { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? LastLogin { get; set; }

    public bool IsActive { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual ICollection<UserAchievement> UserAchievements { get; set; } = new List<UserAchievement>();

  [JsonIgnore]
  public virtual ICollection<UserGenreStat> UserGenreStats { get; set; } = new List<UserGenreStat>();

    public virtual ICollection<UserMovieHistory> UserMovieHistories { get; set; } = new List<UserMovieHistory>();
}